# Site settings
title: TeamWin - TWRP
description: > # this means to ignore newlines until "baseurl:"
  This is the Team Win website and the official home of TWRP! 
  Here you will find the list of officially supported devices
  and instructions for installing TWRP on those devices.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://twrp.me" # the base hostname & protocol for your site
github_username: TeamWin
gems: ['git', 'redcarpet']
# Build settings
markdown: redcarpet
keep_files: [project, twrp_view_all_devices, officialota, datamedia, twrpfaq, whattobackup, whattowipe, securetwrp, removetwrp, noos, contactus/submit.php app/privacypolicy.pdf]
exclude: [project, twrp_view_all_devices, officialota, datamedia, twrpfaq, whattobackup, whattowipe, securetwrp, removetwrp, noos, contactus/submit.php app/privacypolicy.pdf]

collections:
  devices:
    output: true

  faq:
    output: true

  app:
    output: true

  terms:
    output: true
