# Site settings
title: TeamWin - TWRP
description: > # this means to ignore newlines until "baseurl:"
  This is the Team Win website and the official home of TWRP! 
  Here you will find the list of officially supported devices
  and instructions for installing TWRP on those devices.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://twrp.me" # the base hostname & protocol for your site
github_username: TeamWin
plugins: ['git']
# Build settings
keep_files: [project, twrp_view_all_devices, officialota, datamedia, twrpfaq, whattobackup, whattowipe, securetwrp, removetwrp, noos, contactus/submit.php app/privacypolicy.pdf favicon.ico]
exclude: [project, twrp_view_all_devices, officialota, datamedia, twrpfaq, whattobackup, whattowipe, securetwrp, removetwrp, noos, contactus/submit.php app/privacypolicy.pdf README.md]

collections:
  faq:
    output: true

  app:
    output: true

  terms:
    output: true

  oem:
    output: true

  alcatel:
    output: true

  allview:
    output: true

  amazon:
    output: true

  amlogic:
    output: true

  archos:
    output: true

  asus:
    output: true

  bn:
    output: true

  bq:
    output: true

  cat:
    output: true

  dell:
    output: true

  elephone:
    output: true

  ergo:
    output: true

  essential:
    output: true

  fairphone:
    output: true

  gigaset:
    output: true

  google:
    output: true

  hp:
    output: true

  htc:
    output: true

  huami:
    output: true

  huawei:
    output: true

  hyundai:
    output: true

  infinix:
    output: true

  iuni:
    output: true

  kazam:
    output: true

  leeco:
    output: true

  lenovo:
    output: true

  letv:
    output: true

  lg:
    output: true

  lyf:
    output: true

  marshall:
    output: true

  mattel:
    output: true

  meizu:
    output: true

  micromax:
    output: true

  minix:
    output: true

  mobvoi:
    output: true

  motorola:
    output: true

  nextbit:
    output: true

  nokia:
    output: true

  nubia:
    output: true

  nvidia:
    output: true

  omate:
    output: true

  oneplus:
    output: true

  oppo:
    output: true

  oukitel:
    output: true

  pantech:
    output: true

  planet:
    output: true

  quanta:
    output: true

  razer:
    output: true

  realme:
    output: true

  samsung:
    output: true

  silentcircle:
    output: true

  sony:
    output: true

  twrp:
    output: true

  ulefone:
    output: true
  
  umidigi:
    output: true

  unihertz:
    output: true

  vanzo:
    output: true

  vestel:
    output: true

  vivo:
    output: true

  wileyfox:
    output: true

  wingtech:
    output: true

  xiaomi:
    output: true

  yu:
    output: true

  zte:
    output: true

  zuk:
    output: true
